export CUDA_VISIBLE_DEVICES="1"

dataset="/data1/takezawa/dataset/"
model="/data1/takezawa/huggingface/"

language="de-en"
alpha=1


# generate texts by the NS-Watermark.
for gamma in {0.0001,} ; do
    mkdir -p results/wmt_${language}
    python evaluate_wmt.py --method ns_watermark --results results/wmt_${language}/ns_watermark_${gamma}_${alpha}.csv.gz --dataset ${dataset} --model ${model} --alpha ${alpha} --gamma ${gamma} --language ${language}
done		 

# compute z-score of texts generated by the NS-Watermark.
for gamma in {0.0001,} ; do
    mkdir -p results/wmt_${language}/z_score
    python compute_z_score_nllb.py --in_results results/wmt_${language}/ns_watermark_${gamma}_${alpha}.csv.gz --out_results results/wmt_${language}/z_score/ns_watermark_${gamma}_${alpha}.csv.gz --gamma ${gamma} --model ${model}
done

# compute z-score of texts written by humans.
for gamma in {0.0001,} ; do
    mkdir -p results/wmt_${language}/z_score
    python compute_z_score_nllb.py --in_results results/wmt_${language}/ns_watermark_${gamma}_${alpha}.csv.gz --out_results results/wmt_${language}/z_score/human_${gamma}.csv.gz --gamma ${gamma} --model ${model} --human
done

"""
delta=8
for gamma in {0.01,} ; do
    mkdir -p results/wmt_${language}
    python evaluate_wmt.py --method soft_watermark --results results/wmt_${language}/soft_watermark_${gamma}_${delta}.csv.gz --dataset ${dataset} --model ${model} --alpha ${alpha} --gamma ${gamma} --language ${language} --delta ${delta}
done		 

for gamma in {0.01,} ; do
    mkdir -p results/wmt_${language}/z_score
    python compute_z_score_nllb.py --in_results results/wmt_${language}/soft_watermark_${gamma}_${delta}.csv.gz --out_results results/wmt_${language}/z_score/soft_watermark_${gamma}_${delta}.csv.gz --gamma ${gamma} --model ${model}
done
"""
